server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul
  rabbitmq:
    host: 101.132.124.125
    port: 5672
    username: admin
    password: wsy@123456
  sleuth:
    sampler:
      probability: 1.0
zuul:
  FormBodyWrapperFilter:
    pre:
      disable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
